# --------------------------------------
# Hexo Butterfly Theme Configuration
# If you have any questions, please refer to the documentation
# Chinese: https://butterfly.js.org/
# English: https://butterfly.js.org/en/
# --------------------------------------
language: zh-CN

# --------------------------------------
# Navigation Settings
# --------------------------------------

nav:
  logo: /img/logo.png
  display_title: true
  fixed: false

menu:
  首页: / || fas fa-home
  免费节点: /free-nodes/ || fas fa-wifi
  专属节点: /diy-nodes/ || fas fa-tools
  客户端: /clients/ || fas fa-mobile-alt

# --------------------------------------
# Code Blocks Settings
# --------------------------------------

code_blocks:
  theme: light
  macStyle: false
  height_limit: false
  word_wrap: false
  copy: true
  language: true
  shrink: false
  fullpage: false

# Social media links
social:
  # fab fa-github: https://github.com/xxxxx || Github || '#24292e'
  # fas fa-envelope: mailto:xxxxxx@gmail.com || Email || '#4a7dbe'

# --------------------------------------
# Image Settings
# --------------------------------------

favicon: /img/favicon.png

avatar:
  img: /img/butterfly-icon.png
  effect: false

disable_top_img: true
default_top_img: false
index_img: false
archive_img:
tag_img:
tag_per_img:
category_img:
category_per_img:
footer_img: false
background:

cover:
  index_enable: false
  aside_enable: true
  archives_enable: true
  default_cover:

error_img:
  flink: /img/friend_404.gif
  post_page: /img/404.jpg

error_404:
  enable: false
  subtitle: '页面不存在'
  background: /img/error-page.png

post_meta:
  page:
    date_type: created
    date_format: date
    categories: true
    tags: false
    label: true
  post:
    position: left
    date_type: both
    date_format: date
    categories: true
    tags: true
    label: true

# --------------------------------------
# Index page settings
# --------------------------------------

index_site_info_top:
index_top_img_height:

subtitle:
  enable: false
  effect: true
  typed_option:
  source: false
  sub:

index_layout: 3

index_post_content:
  method: 3
  length: 500

# --------------------------------------
# Post Settings
# --------------------------------------

toc:
  post: true
  page: false
  number: true
  expand: false
  style_simple: false
  scroll_percent: true

post_copyright:
  enable: true
  decode: false
  author_href:
  license: CC BY-NC-SA 4.0
  license_url: https://creativecommons.org/licenses/by-nc-sa/4.0/

reward:
  enable: false
  text:
  QR_code:

post_edit:
  enable: false
  url:

related_post:
  enable: true
  limit: 6
  date_type: created

post_pagination: 1

noticeOutdate:
  enable: false
  style: flat
  limit_day: 365
  position: top
  message_prev: 已经过了
  message_next: 天，文章内容可能已过时。

# --------------------------------------
# Footer Settings
# --------------------------------------
footer:
  nav:
  owner:
    enable: true
    since: 2025
  copyright:
    enable: true
    version: true
  custom_text:

# --------------------------------------
# Aside Settings
# --------------------------------------

aside:
  enable: true
  hide: false
  button: true
  mobile: true
  position: right
  display:
    archive: false
    tag: true
    category: true
  card_author:
    enable: false
    description:
    button:
      enable: true
      icon: fab fa-github
      text: 关注我
      link: https://github.com/xxxxxx
  card_announcement:
    enable: false
    content: 这是我的博客
  card_recent_post:
    enable: true
    limit: 5
    sort: date
    sort_order:
  card_newest_comments:
    enable: false
    sort_order:
    limit: 6
    storage: 10
    avatar: true
  card_categories:
    enable: true
    limit: 8
    expand: none
    sort_order:
  card_tags:
    enable: true
    limit: 40
    color: false
    orderby: random
    order: 1
    sort_order:
  card_archives:
    enable: false
    type: monthly
    format: MMMM YYYY
    order: -1
    limit: 8
    sort_order:
  card_post_series:
    enable: true
    series_title: false
    orderBy: 'date'
    order: -1
  card_webinfo:
    enable: false
    post_count: true
    last_push_date: true
    sort_order:
    runtime_date:

# --------------------------------------
# Bottom right button
# --------------------------------------

rightside_bottom:

translate:
  enable: false
  default: 繁
  defaultEncoding: 2
  translateDelay: 0
  msgToTraditionalChinese: '繁'
  msgToSimplifiedChinese: '簡'

readmode: true

darkmode:
  enable: true
  button: true
  autoChangeMode: false
  start:
  end:

rightside_scroll_percent: false

rightside_item_order:
  enable: false
  hide:
  show:

rightside_config_animation: true

# --------------------------------------
# Global Settings
# --------------------------------------

anchor:
  auto_update: false
  click_to_scroll: false

photofigcaption: false

copy:
  enable: true
  copyright:
    enable: false
    limit_count: 150

wordcount:
  enable: false
  post_wordcount: true
  min2read: true
  total_wordcount: true

busuanzi:
  site_uv: true
  site_pv: true
  page_pv: true

# --------------------------------------
# Math
# --------------------------------------

math:
  use:
  per_page: true
  hide_scrollbar: false
  mathjax:
    enableMenu: true
    tags: none
  katex:
    copy_tex: false

# --------------------------------------
# Search
# --------------------------------------

search:
  use:
  placeholder: 搜索

# --------------------------------------
# Share System
# --------------------------------------

share:
  use: sharejs
  sharejs:
    sites: facebook,twitter,wechat,weibo,qq
  addtoany:
    item: facebook,twitter,wechat,sina_weibo,facebook_messenger,email,copy_link

# --------------------------------------
# Comments System
# --------------------------------------

comments:
  use:
  text: true
  lazyload: false
  count: false
  card_post_count: false

# --------------------------------------
# Chat Services
# --------------------------------------

chat:
  use:
  rightside_button: false
  button_hide_show: false

# --------------------------------------
# Analysis
# --------------------------------------

baidu_analytics:
google_analytics:
cloudflare_analytics:
microsoft_clarity:
umami_analytics:
  enable: false
  serverURL:
  website_id:
  option:
  UV_PV:
    site_uv: false
    site_pv: false
    page_pv: false
    token:

# --------------------------------------
# Advertisement
# --------------------------------------

google_adsense:
  enable: false
  auto_ads: true
  js: https://pagead2.googlesyndication.com/pagead/js/adsbygoogle.js
  client:
  enable_page_level_ads: true

ad:
  index:
  aside:
  post:

# --------------------------------------
# Verification
# --------------------------------------

site_verification:

# --------------------------------------
# Beautify / Effect
# --------------------------------------

category_ui:
tag_ui:

rounded_corners_ui: true
text_align_justify: false

mask:
  header: true
  footer: true

preloader:
  enable: false
  source: 1
  pace_css_url:

enter_transitions: true
display_mode: light

beautify:
  enable: false
  field: post
  title_prefix_icon:
  title_prefix_icon_color:

font:
  global_font_size:
  code_font_size:
  font_family:
  code_font_family:

blog_title_font:
  font_link:
  font_family:

hr_icon:
  enable: true
  icon:
  icon_top:

activate_power_mode:
  enable: false
  colorful: true
  shake: true
  mobile: false

canvas_ribbon:
  enable: false
  size: 150
  alpha: 0.6
  zIndex: -1
  click_to_change: false
  mobile: false

canvas_fluttering_ribbon:
  enable: false
  mobile: false

canvas_nest:
  enable: false
  color: '0,0,255'
  opacity: 0.7
  zIndex: -1
  count: 99
  mobile: false

fireworks:
  enable: false
  zIndex: 9999
  mobile: false

click_heart:
  enable: false
  mobile: false

clickShowText:
  enable: false
  text:
  fontSize: 15px
  random: false
  mobile: false

# --------------------------------------
# Lightbox Settings
# --------------------------------------

lightbox:

# --------------------------------------
# Tag Plugins settings
# --------------------------------------

series:
  enable: false
  orderBy: 'title'
  order: 1
  number: true

abcjs:
  enable: false
  per_page: true

mermaid:
  enable: false
  code_write: false
  theme:
    light: default
    dark: dark

chartjs:
  enable: false
  fontColor:
    light: 'rgba(0, 0, 0, 0.8)'
    dark: 'rgba(255, 255, 255, 0.8)'
  borderColor:
    light: 'rgba(0, 0, 0, 0.1)'
    dark: 'rgba(255, 255, 255, 0.2)'
  scale_ticks_backdropColor:
    light: 'transparent'
    dark: 'transparent'

note:
  style: flat
  icons: true
  border_radius: 3
  light_bg_offset: 0

# --------------------------------------
# Other Settings
# --------------------------------------

pjax:
  enable: false
  exclude:

aplayerInject:
  enable: false
  per_page: true

snackbar:
  enable: false
  position: bottom-left
  bg_light: '#49b1f5'
  bg_dark: '#1f1f1f'

instantpage: false

lazyload:
  enable: false
  field: site
  placeholder:
  blur: false

pwa:
  enable: false
  manifest:
  apple_touch_icon:
  favicon_32_32:
  favicon_16_16:
  mask_icon:

Open_Graph_meta:
  enable: true
  option:

structured_data: true
css_prefix: true

inject:
  head:
  bottom:

CDN:
  internal_provider: local
  third_party_provider: jsdelivr
  version: false
  custom_format:
  option: